### ISSUE TITLE
Fields need validation ability

### ISSUE THREAD

**Issue by gregoryjjb** [gregoryjjb/vicini-web#10]
This will probably be a function of all values like the other things (visible, enabled, etc)

**Comment by JeremySorensen** [comment]
Can we do this?
 have a validation result with a status and a message, and the validation
field has to return it, if status is ok or true then validation succeeded
otherwise the control is highlighted and the message is shown and all other
controls are disabled. Message can be in a tool tip or something

Of course there is probably some existing validation thing you just playing
into

On Aug 14, 2018 10:44 AM, "Greg Brisebois" <notifications@github.com> wrote:

This will probably be a function of all values like the other things
(visible, enabled, etc)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gregoryjjb/vicini-web/issues/10>, or mute the thread

**Comment by gregoryjjb** [comment]
That's exactly how I would do it, except instead of returning two things it would just be an empty string (or some other falsy value) or an error string if there is an error. That's how I implemented it in Scott's framework and it worked great.

**Comment by JeremySorensen** [comment]
Then in the words of Captain Jean Luc Picard, "Make it so"

**Comment by gregoryjjb** [comment]
Specified behavior implemented in 1421c3ea57ff9885814f6e3ba109d31e440390f6.
